theme: jekyll-theme-modernist
url: https://alexfroio.github.io/iamalexfroio.github.io/
title: Alexandre Hernandez Froio
description: hire alex froio or just like, don't? I'm a webpage, not your boss.
