theme: jekyll-theme-hacker
url: https://alexfroio.github.io/iamalexfroio.github.io/
title: Alexandre Hernandez Froio
description: Electrical Engineer interested in opportunities in the medical devices industry
